
/**************************************************************
 *	
 *	BgSong, 8 bit, 11025Hz,
 *	1 channel, 1032768 bytes/channel
 *	Total Size: 1 * 1032768 + 4 (header) = 1032812 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Lamine\Desktop\BgSong.wav
 *	Time-stamp: Mon Nov 21 16:08:27 2011
 *	
 **************************************************************/

#ifndef __BGSONGH__
#define __BGSONGH__

#define BGSONGFREQ 11025
#define BGSONGLEN 1032768

extern const unsigned char BgSong[1032768];

#endif /* __BGSONGH__ */
