
/**************************************************************
 *	
 *	cat_screech, 8 bit, 11025Hz,
 *	1 channel, 8152 bytes/channel
 *	Total Size: 1 * 8152 + 4 (header) = 8196 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Lamine\Desktop\cat_screech.wav
 *	Time-stamp: Fri Dec 02 19:17:24 2011
 *	
 **************************************************************/

#ifndef __CAT_SCREECHH__
#define __CAT_SCREECHH__

#define CAT_SCREECHFREQ 11025
#define CAT_SCREECHLEN 8152

extern const unsigned char cat_screech[8152];

#endif /* __CAT_SCREECHH__ */
