
/**************************************************************
 *	
 *	explosion, 8 bit, 11025Hz,
 *	1 channel, 19872 bytes/channel
 *	Total Size: 1 * 19872 + 4 (header) = 19916 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Lamine\Desktop\explosion.wav
 *	Time-stamp: Mon Nov 28 22:14:41 2011
 *	
 **************************************************************/

#ifndef __EXPLOSIONH__
#define __EXPLOSIONH__

#define EXPLOSIONFREQ 11025
#define EXPLOSIONLEN 19872

extern const unsigned char explosion[19872];

#endif /* __EXPLOSIONH__ */
