
/**************************************************************
 *	
 *	victory, 8 bit, 11025Hz,
 *	1 channel, 63887 bytes/channel
 *	Total Size: 1 * 63887 + 4 (header) = 63931 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Lamine\Desktop\victory.wav
 *	Time-stamp: Mon Nov 28 21:54:38 2011
 *	
 **************************************************************/

#ifndef __VICTORYH__
#define __VICTORYH__

#define VICTORYFREQ 11025
#define VICTORYLEN 63887

extern const unsigned char victory[63887];

#endif /* __VICTORYH__ */
